// Code generated by "stringer -type=tokenType -trimprefix=tok"; DO NOT EDIT.

package kdl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokEOF-0]
	_ = x[tokErr-1]
	_ = x[tokInt-2]
	_ = x[tokFloat-3]
	_ = x[tokNewline-4]
	_ = x[tokIgnoreNode-5]
	_ = x[tokSpace-6]
	_ = x[tokIdentifier-7]
	_ = x[tokString-8]
	_ = x[tokEqual-9]
	_ = x[tokOpenBracket-10]
	_ = x[tokCloseBracket-11]
}

const _tokenType_name = "EOFErrIntFloatNewlineIgnoreNodeSpaceIdentifierStringEqualOpenBracketCloseBracket"

var _tokenType_index = [...]uint8{0, 3, 6, 9, 14, 21, 31, 36, 46, 52, 57, 68, 80}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
